FILE_1 = /home/vinte/cheatersdemise/SuspiciousPatternId/1/1.npy
FILE_2 = /home/vinte/cheatersdemise/SuspiciousPatternId/2/2.npy
FILE_5 = /home/vinte/cheatersdemise/SuspiciousPatternId/5/5.npy
FILE_10 = /home/vinte/cheatersdemise/SuspiciousPatternId/10/10.npy

run:
	python3 MainCD.py 1
	python3 MainCD.py 2
	python3 MainCD.py 5
	python3 MainCD.py 10
	
